name: FlowDB
url: https://flowdb.dev
hook_attributes:
  url: https://api.flowdb.dev/webhooks/github
redirect_url: https://flowdb.dev/integrations/github/callback
public: false
default_events:
  - pull_request
  - push
  - check_suite
default_permissions:
  pull_requests: write
  checks: write
  statuses: write
